# Font configuration (changes require restart)
font:
  normal:
    family: JetBrains Mono Nerd Font 

env:
  TERM: xterm-256color

import:
  - ~/.config/alacritty/theme.yml
  - ~/.config/alacritty/window.yml
  - ~/.config/alacritty/hotkeys.yml

